name: patient_app
description: Flutter App to manage patients data

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^0.2.1
  auto_animated: ^1.2.3
  auto_size_text: ^2.1.0
  cached_network_image: ^2.0.0-rc
  charts_flutter: ^0.10.0
  cloud_firestore: ^2.2.1
  cupertino_icons: ^1.0.2
  easy_gradient_text: ^1.0.0
  email_auth: ^1.0.0
  file_picker: ^3.0.2+2
  firebase: ^9.0.1
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.1
  firebase_database: ^6.0.0
  firebase_storage: ^8.1.1
  fl_chart: ^0.36.2
  flare_flutter: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_hooks: ^0.18.2
  flutter_icons: ^1.1.0
  flutter_local_notifications: ^5.0.0+1
  flutter_signin_button: ^1.0.0
  flutter_staggered_animations: ^0.1.2
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  form_field_validator: ^1.1.0
  get: ^4.6.1
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^4.5.9
  hooks_riverpod: ^1.0.3
  image_picker: ^0.8.4+5
  intl: ^0.17.0
  local_auth: ^1.1.10
  lottie: ^1.0.1
  page_transition: ^1.1.7+6
  path: ^1.8.0
  percent_indicator: ^2.1.7+2
  provider: ^5.0.0
  qr_flutter: ^3.2.0
  qrscan: ^0.2.22
  responsive_widgets: ^0.1.10
  rflutter_alert: ^2.0.2
  shared_preferences: ^2.0.6

flutter_native_splash:
  image: assets/blue.png
  color: "42a5f5"
  fill: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/category/
    - assets/onBoardDoc.png
    - assets/images/docprofile/
    - assets/images/docinfo/
    - assets/animations/Success Check.flr
    - assets/animations/
    - assets/sound/

  fonts:
    - family: avenir
      fonts:
        - asset: assets/font/avenir.ttf
    - family: Ic
      fonts:
        - asset: assets/fonts/ic/ic_medicine.ttf
    - family: Angel
      fonts:
        - asset: assets/fonts/neu/Angel Signature.ttf
